'use client'

import dynamic from 'next/dynamic'
import { setBasePath } from '@shoelace-style/shoelace/dist/utilities/base-path'

setBasePath('https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.83/dist/')


export const SlAlert = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlAlert), { ssr: false })
export const SlAnimatedImage = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlAnimatedImage), { ssr: false })
export const SlAvatar = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlAvatar), { ssr: false })
export const SlBadge = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlBadge), { ssr: false })
export const SlBreadcrumb = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlBreadcrumb), { ssr: false })
export const SlAnimation = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlAnimation), { ssr: false })
export const SlButton = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlButton), { ssr: false })
export const SlBreadcrumbItem = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlBreadcrumbItem), { ssr: false })
export const SlButtonGroup = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlButtonGroup), { ssr: false })
export const SlCard = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlCard), { ssr: false })
export const SlCheckbox = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlCheckbox), { ssr: false })
export const SlColorPicker = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlColorPicker), { ssr: false })
export const SlDetails = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlDetails), { ssr: false })
export const SlDialog = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlDialog), { ssr: false })
export const SlDivider = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlDivider), { ssr: false })
export const SlDrawer = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlDrawer), { ssr: false })
export const SlDropdown = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlDropdown), { ssr: false })
export const SlFormatBytes = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlFormatBytes), { ssr: false })
export const SlFormatDate = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlFormatDate), { ssr: false })
export const SlFormatNumber = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlFormatNumber), { ssr: false })
export const SlIcon = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlIcon), { ssr: false })
export const SlIconButton = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlIconButton), { ssr: false })
export const SlImageComparer = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlImageComparer), { ssr: false })
export const SlInclude = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlInclude), { ssr: false })
export const SlInput = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlInput), { ssr: false })
export const SlMenu = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlMenu), { ssr: false })
export const SlMenuItem = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlMenuItem), { ssr: false })
export const SlMenuLabel = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlMenuLabel), { ssr: false })
export const SlMutationObserver = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlMutationObserver), { ssr: false })
export const SlPopup = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlPopup), { ssr: false })
export const SlProgressBar = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlProgressBar), { ssr: false })
export const SlProgressRing = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlProgressRing), { ssr: false })
export const SlQrCode = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlQrCode), { ssr: false })
export const SlRadio = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlRadio), { ssr: false })
export const SlRadioButton = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlRadioButton), { ssr: false })
export const SlRadioGroup = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlRadioGroup), { ssr: false })
export const SlRating = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlRating), { ssr: false })
export const SlRelativeTime = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlRelativeTime), { ssr: false })
export const SlRange = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlRange), { ssr: false })
export const SlResizeObserver = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlResizeObserver), { ssr: false })
export const SlSelect = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlSelect), { ssr: false })
export const SlSkeleton = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlSkeleton), { ssr: false })
export const SlSpinner = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlSpinner), { ssr: false })
export const SlSplitPanel = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlSplitPanel), { ssr: false })
export const SlSwitch = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlSwitch), { ssr: false })
export const SlTab = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlTab), { ssr: false })
export const SlTabGroup = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlTabGroup), { ssr: false })
export const SlTabPanel = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlTabPanel), { ssr: false })
export const SlTag = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlTag), { ssr: false })
export const SlTextarea = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlTextarea), { ssr: false })
export const SlTooltip = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlTooltip), { ssr: false })
export const SlTree = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlTree), { ssr: false })
export const SlTreeItem = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlTreeItem), { ssr: false })
export const SlVisuallyHidden = dynamic(() => import('node_modules/@shoelace-style/shoelace/dist/react').then(module => module.SlVisuallyHidden), { ssr: false })
