import { Work_Sans } from '@next/font/google'
import 'tailwind.css'

import '@shoelace-style/shoelace/dist/themes/light.css'
import { setBasePath } from '@shoelace-style/shoelace/dist/utilities/base-path'

setBasePath('https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.83/dist/')

const appFontFamily = Work_Sans({ subsets: ["latin"], weight: 'variable' })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={appFontFamily.className}>
      <head>
        <title>Events Society</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className='h-screen overflow-y-hidden'>{children}</body>
    </html>
  )
}
